moo-man/WFRP4e-FoundryVTT

- modules/actor/sheet/actor-sheet.js
Removed focusout() and keydown() for '.skill-advances' and replaced with change().  Updated _render() to set focus for the recorded data-item-id after sheet renders.
> Updated actor-sheet.js to better handle tabbing between skill advances

- css/wfrp4e.css
This fixes following issues:
* import/export buttons in calendar settings too small
* white text on bright background in events window of calendar/weather
* white text on bright background in quest preview on some tabs
> Fix styling in Forien's Quest Log and Calendar/Weather

- modules/actor/actor-wfrp4e.js
I kept getting this while working on v8 updates to GM Toolkit macros.  
> foundry.js:19241 You are calling PlaceableObject#update which has been deprecated in favor of Document#update or Scene#updateEmbeddedDocuments. Support will be removed in 0.9.0 
To reproduce, update an actor that has a linked token in the viewed scene (eg, current Fortune directly via character sheet or Reset Fortune macro).  The deprecation warning comes up in console.
> Fix PlaceableObject#update deprecation warning

- modules/system/utility-wfrp4e.js
Hi,
working on the translation, I found out that the condition links aren't working properly.
I noticed that yesterday it was created an issue (#878) about it and this pull request could be a solution for it.
I removed also a line of code where the condition name is splitted by single space before finding its key. The reason why I removed it is that in languages like Italian the "Unconscious" condition is translated like "Privo di Sensi" which are 3 words separated by single spaces. So, for instance, in the translated strings, we just need to write `@Condition[Privo di Sensi]` instead of `@Condition[Unconscious]`.
I hope it helps,
W1zZo
> Condition Link Adjustments for other languages

- modules/item/item-wfrp4e.js
The variable in _addProperties was named incorrectly, which caused issues when selecting ammunition that contains a flaw. This flaw was not being properly transferred to the weapon.
> Fix error in adding flaws from _addProperties

- lang/en.json
- modules/actor/sheet/character-sheet.js
- modules/system/utility-wfrp4e.js
I've added some small code to prevent xp going into negative, also added a i18n message and ui errors to display on click. It's not my most DRY code, but I didn't want to go adding a function in the sheet. I could add it in the utility class if that works better for you?
```
static checkValidAdvancement(total, spent, action, item) {
if(total - spent < 0) {
ui.notifications.error(game.i18n.format("ACTOR.AdvancementError", { action: action, item: item }));
return false;
} else {
return true;
}
}
```
for example
> Add error messages advancement functions to prevent negative xp

- modules/actor/actor-wfrp4e.js
Fixes #962 typo in javascript referring to `createDate` when it should be `createData`.
> Fixes #962 typo in javascript

- modules/actor/actor-wfrp4e.js
- modules/system/rolls/trait-test.js
- modules/system/rolls/weapon-test.js
Currently: 
- If the Charging checkbox is selected on a Weapon test, that selection is carried into the test / opposed test predata results.  
- This does not happen for Trait Tests where charging is an option.  
- In both cases the Advantage change for toggling Charging is applied as expected. 
This change: 
- passes the Charging checked status from Trait Test dialogs through to TraitTest results
- removes duplicate predata.charging reference in WeaponTest
> Persist Charging option status in Trait Test data

- modules/hooks/chat.js
This fixes the "Rest & Recover Wounds" button not recovering the wounds when dragging them from the chat.
> Fixed Rest & Recover Wounds

- .gitignore
- modules/system/audio-wfrp4e.js
- modules/system/combat.js
Hello, learning to develop on this project. Starting simple by eliminating a couple of exceptions that I noticed.
1. When starting a combat encounter without a scene or tokens, undefined object exceptions fire in `CombatHelpers.startTurnChecks()` for the `turn` object and `CombatHelpers.checkEndTurnConditions()` for the `combatant` object. Added tests for undefined to prevent these exceptions, and write a console warning instead in `startTurnChecks()`.
2. Seems like all the sound files are removed from `sounds.txt`, so `WFRP_Audio.PlayContextAudio` by default always throws an undefined object and also causes an HTTP 404. Added test for undefined `sound.file` to prevent both of those in favor of a console warning.
3. Set git to ignore the `wfrp4e.lock` file if you happen to have the system …
> Guard against undefined objects during encounters

- css/wfrp4e.css
Replaces simple calendar classic theme with the one that matches system style. Both full and compact views are updated.
For new setups Simple Calendar offers Dark theme by default, which works ok with the WFRP system but looks alien. Classic theme intended to mimic the DnD5e system style, so I chose to replace it to provide system look.
> Improve compatibility with Simple Calendar

- modules/actor/sheet/character-sheet.js
When activating an untrained career skill on FVTT v10.283 and WFRP4e v6.1.1 the folllowing error occurs:
> Fix error when adding untrained skill

- static/templates/apps/chargen/career.html
A translation was missing in the career selector of the character generator.
> Added translation

- static/css/wfrp4e.css
[Chat Commander](https://foundryvtt.com/packages/_chatcommands) is a chat command autocompletion/helper module.
It creates a phantom textarea for its own use, but it receives the WFRP4e's border style, which shows up in the middle of the box as shown on the video below.
Proposed changes would ensure that `border` attribute is applied only to the real chat message textarea.
> CSS compatibility for module Chat Commander

- modules/actor/sheet/actor-sheet.js
- modules/hooks/journal.js
- modules/item/item-sheet.js
- modules/system/chat-wfrp4e.js
- modules/system/config-wfrp4e.js
- modules/system/utility-wfrp4e.js
- static/css/wfrp4e.css
Allows using `@Property[key]{label)` format to create a clickable links.
When clicked, they will push Property's description to chat, similarly to `@Condition` syntax.
> Add clickable property link for rich text editors

- modules/actor/sheet/actor-sheet.js
- modules/actor/sheet/character-sheet.js
- static/templates/actors/actor-combat.hbs
- static/templates/actors/vehicle/vehicle-main.hbs
When a player has arrows in several containers, game doesn't let them know which arrows are they using. The only distinction would be the quantity or the name.
This poses several issues, especially if some of the ammunition was left behind in a Tavern, or if people play with additional rules for quivers etc. 
This PR adds container's name to the ammo select to alleviate all of those issues.
> Show ammunition's location in the ammo select dropdown menu

- modules/model/item/weapon.js
- static/lang/en.json
Basically #1841 but made from `effect-refactor` branch, so it can be merged.
Closes #1841
> fixed `ammoRange` typo and added graceful fallback to not block opening

- modules/model/actor/standard.js
Right now, on effects such as `Prepare Data`, the `args.actor` holds Actor's Data Model. This breaks some effects that rely on this, such as `Malaise` that uses `args.actor.hasCondition()` and `args.actor.addCondition()`.
Proposed PR will change it instead to Actor's actual instance so effect scripts can have unchanged access to the entire Actor Document.
> Pass actual ActorWfrp4e instance to scripts 

- modules/model/item/weapon.js
Vehicles don't implement the `StandardActorModel` which, by using `StandardDetailsModel`, defines `details.size`. So before trying to access that, let's first check if the actor implements the correct Data Model and only then test the size.
Fixes #1854
> Fix `mooSizeDamage` Setting for Vehicles

- modules/actor/actor-wfrp4e.js
- modules/actor/sheet/actor-sheet.js
- modules/model/item/disease.js
Refactored some of the code responsible for handling Actor's diseases. 
For the most part, changes could be described as one of the following:
- Styling improvements
- Reducing code duplication (DRY)
- Improving readability and adding JSDoc comments
- Replacing `.then()` syntax with `await` syntax inside `async` function
But there are also several instances of actual changes and improvements, such as:
- Adding `await` in places, where lack of it could lead to data loss and/or race conditions
- Fixing actual errors.
---
**More info in commit [review/comments](https://github.com/moo-man/WFRP4e-FoundryVTT/pull/1851/files).**
---
I realize that **most of these methods** will need an additional pass when Disease are migrated (currently, I am unable to created new Items on this branch because …
> Disease code refactor (Part 1)

- modules/system/opposed-test.js
Added support for the following triggers:
- `preOpposedAttacker`
- `preOpposedDefender`
- `opposedAttacker`
- `opposedDefender`
For Active Effect Scripts with `Item` as their `Document Type`
> Add `preOpposed*` and `opposed*` triggers for Item Effects

- modules/system/combat.js
This PR adds several Hooks related to Combat that 3rd party modules can use.
Hooks match up with corresponding Active Effect triggers, always happening _after_ effects, and having the same arguments. 
This way, 3rd party modules could hook up (pun intended) to the common, system defined events, instead of trying to engineer their own checks of when turn starts, when it ends, what update says what etc.
Added Hooks:
- `wfrp4e:startCombat`
- `wfrp4e:startTurn`
- `wfrp4e:endTurn`
- `wfrp4e:endRound`
- `wfrp4e:endCombat`
> Add Combat Hooks

- modules/hooks/chat.js
There is a possible to encounter error to `/pay` command.
When command is provided with an Actor's name, it breaks if there exist a player without assigned character.
This PR fixes that issue
> Fix `/pay amount actor` command

- modules/hooks/hotbarDrop.js
When one player created a macro (dragging a `Hand Weapon`) from sheet to Hotbar, it would create macro as that player with only them having permission.
If then another player drags their `Hand Weapon`, they can see macro being put in Hotbar, but they do not have enough permissions to execute it.
Simply adding ` && m.canExecute` to find conditions is more than enough. If player can execute a macro, it will be used, if not, new macro will be created
This would also work, but I have several reasons to prefer the other solution:
1. I believe some people prefer having more control over their hotbar, especially choosing names, icons etc to their liking, so every user having their own macro that they are Owner of is in my opinion better. 
2. It would not work on already created macros without a …
> Fix unusable drop macro because it existed without permission

- modules/actor/actor-wfrp4e.js
This PR allows setupSkill and setupCharacteristic to specify the default value of Hit Location. Previously it always showed "Roll".
My use case is my Endeavours module. Some require a weapon test that isn't an attack, so no need to roll location. Mainly useful to avoid confusing weapon critical/fumble messages.
> Default value for hitLocation

- modules/apps/name-gen.js
- static/lang/en.json
This allows the name generator to use localized genders. "male" and "female" can still be used.
Tested in the character creator and the name button of the NPC and Creature sheets.
> Localized Gender for Name Generator

- modules/model/actor/components/status.js
- modules/model/actor/standard.js
The Advantage Cap PR I sent earlier was made before the effect refactor update. This one works after the update.
Also, DataModel not having advantage.max creates some issues with the advantage token bar. It isn't recognized as a bar and thus it disappears if the token is updated in any way (changing the token's name, for example).
> Advantage cap update

- modules/actor/actor-wfrp4e.js
- modules/system/utility-wfrp4e.js
Minor change I need for scrolls to work with spell's effects. 
Since scrolls are not spells and only mimic them, for Chat Cards to know what effects to trigger I need them to point to Compendium UUID.
This PR changes `Actor.applyEffect` method so it can load any UUID with `await fromUuid()` instead `fromUuidSync()`.
This is completely safe since `Actor.applyEffect` is `async` already, so there is no reason to use `fromUuidSync()` anyway.
> Allow compendium effects

- modules/apps/chargen/career.js
- modules/apps/chargen/skills-talents.js
- modules/system/config-wfrp4e.js
- modules/system/utility-wfrp4e.js
- static/lang/en.json
Two changes suggestions in order to make Sea of Claws Chargen work better.
1. Allows all three Norse subspecies to share a rollable table, as defined in their config
2. Allows species and subspecies to have optional Talent replacement 
**SoC, page 56 (bottom left):**
> A Skaeling Character who generates the Pure Soul Talent as a Random Talent may take the Mark of Khorne instead.
> Allow talent replacement and predefined career table

- modules/system/opposed-test.js
Fixes non-damage Opposed Tests (for example Opposed Strength Test or Opposed Perception/Stealth Test) having undefined damage breakdown, which caused Type Error. 
- Fixes #2006
> Fix non-damage opposed tests undefined breakdown error

- modules/actor/mixin.js
- modules/system/combat.js
@silentmark 
@Forien 
Considering this change to fix #2015 but cautious about the changes to the arguments given to the scripts.
Alternatively, if this is an issue, a separate function, such as `runScriptsOwnerOnly` that calls `runScripts` if user is the owner, can be used.
> initial runScripts change

- modules/actor/sheet/actor-sheet.js
- modules/hooks/ready.js
- modules/system/aoe.js
- modules/system/area-helpers.js
- modules/system/chat-wfrp4e.js
My magic scrolls cast spells by using their world or compendium UUID as reference, so I would need all instances of where their effects are loaded to be `await fromUuid`. 
Fortunately this fix for area is not disruptive as most changes were already within an async function, or were an endpoint where it doesn't matter.
> Allow area effects to be loaded async so scrolls can use them

- modules/actor/sheet/actor-sheet.js
- modules/hooks/init.js
- modules/model/item/generic.js
- static/templates/items/item-aspect-sheet.hbs
- static/templates/partials/aspect-list.hbs
This PR allows aspects to be triggered by the system, while letting modules define the implementation. 
On the same note, I am unsure if the following schema even belongs to the Generic Aspect Model, since the model itself is abstract and the children should define their own schema (and may not even use this one)
```js
schema.use = new fields.SchemaField({
formula : new fields.StringField({initial : ""}),
skill : new fields.StringField({initial : ""})
})
```
> Generic aspect usage and sheet trigger

- modules/system/opposed-test.js
A minor improvement that will allow to modify result of opposed test in preOpposedAttacker / preOpposedDefender effects same way as weapon's length does.
> opposed test postmodifiers improvement.

- static/moo/items.json
Ticking every box from Penetrating Values to Item Changes in the homebrew settings didn't seem to do anything to Core items, so I dug through the files a bit and came up with this:
- The id's in items.json didn't seem to match the ones in the compendium so I changed them.
- Accessing (and changing) items through the "data" field was deprecated in v10 so I changed it to "system".
- Same changes apply to Archives vol1 items, but Arcane Marks are left unchanged.
- Bonus spelling fixes to please Tzeentch.
> mooHomebrewItemChanges items.json fixes

- modules/apps/travel-distance-wfrp4e.js
Modify `loadTravelData()` function to load `.json` files only, preventing errors with `.json.gz` files stored for nginx static compression.
> Load travel data files with .json extension only

- modules/actor/actor-wfrp4e.js
This PR fixes Corruption Test not firing after closing Test Dialog window. 
Also contains minor fix for duplicate `attacker` key in args object passed to `takeDamage` and `applyDamage` scripts & hook (browsers probably didn't bother, but my IDE threw a tantrum)
> Fix for Corruption test

- modules/actor/sheet/actor-sheet.js
- modules/model/item/disease.js
- modules/model/item/injury.js
- src/apps/sheets/actor/standard-sheet.js
- static/templates/sheets/actor/tabs/actor-effects.hbs
Injury could not be decremented at all due to missing method of `ActorSheetWFRP4e`. I assume the method was removed along the rework of the disease handling.
**Related issues**
- Fixes #2275
I changed the entire Injury handling to also happen in the Data Model and mimic how the diseases are handled.
Since there was no old code to compare and I'm lazy, **I am not aware if there should be any additional checks when Injury is "finished"**.
When Disease with Lingering symptom is finishing, there should be Test Dialog popping up for Endurance. This threw an error, so I fixed it
Not related to any bug, but I need that for my module, because I rely on the returned value, and when disease turned from `incubation` to `duration`, the object returned from `decrement` did not reflect that.
> Important changes to handling Disease and Injuries

- modules/apps/market-wfrp4e.js
- modules/system/chat-wfrp4e.js
- modules/system/utility-wfrp4e.js
- static/lang/en.json
- static/templates/chat/market/market-pay.hbs
- static/templates/chat/market/market-settlement.hbs
- static/templates/chat/post-item.hbs
This Pull Request provides 4 QoL changes to the Market workflow, all centered around giving more context to Payment and Availability Tests.
I wanted to create my players a "Menu" of an Inn, using either pinned Chat Message or a Journal (irrelevant), which would include multiple options of `@Pay` messages, for example:
```
@Pay[1ss]{Breakfast}
@Pay[5bp]{Pint of quality beer}
```
However, system would not allow players to click on those buttons.
<ins>This Pull Requests allows Players to click that button and pay the amount.</ins>
Whenever someone rolls for availability or purchases a posted Item, there is no context clue as to what item that is. While it might not matter with single item, sometimes several Items could be posted to chat (for example several types of draughts, arrows or …
> Various Market QoL improvements

- modules/apps/stat-parser.js
Allows parser to import statblocks with `–` signs by changing `NaN` values to `0` when parsing Characteristics
> Fix StatBlockParser when Characteristics is absent

- modules/system/rolls/cast-test.js
- modules/system/rolls/channel-test.js
As far as I know, miscasts do not stack, but only worst appears.
Wasn't sure about grimoire, left it with unique key.
> Make tables path uniform for all miscasts across both Cast and Channel Tests

- src/hooks/init.js
- src/model/item/generic.js
- src/system/tables-wfrp4e.js
Fixes:
- Errors when trying to preload missing partials: https://discord.com/channels/787396882875416606/787397718339223603/1369335284222787754
- Non-Item RollTable results not showing up: https://discord.com/channels/170995199584108546/697845419593695362/1369628595273863208
- Item RollTable results showing an additional Chat Message with `[object Object]`
Changes:
- If Text Rolltable Result has a `name` (title, sort of), the resulting Chat Message also displays that.
> Morning fixes

- src/canvas/token-ruler.js
This PR adds colors for the ruler segment. The same as the grid highlight. Specially useful for gridless maps.
Also used the same colors for immobile. Added a blue color for blink and displace.
I noticed that in gridless maps, many times when moving exactly to the speed limits (walk and run) it shows the next color. I think that is because there are some unseen decimals.
Ideally, the cursor should snap to that limit when it's close, like drag ruler did. But I have no idea on how to do that.
> Colors for ruler segment

- docs/pages/effects/effects.md
- docs/pages/fan-modules.md
- docs/pages/macros.md
- docs/pages/modules/chat-commander.md
- docs/pages/modules/fan-maps.md
- docs/pages/modules/forien-armoury.md
- docs/pages/modules/gm-toolkit.md
- docs/pages/modules/more-subspecies.md
- docs/pages/modules/mutant-handbook.md
- docs/pages/modules/night-vision.md
- docs/pages/modules/npc-generator.md
- docs/pages/modules/tah-wfrp4e.md
- docs/pages/modules/unofficial-grimoire.md
- docs/pages/modules/warriors-of-salvation.md
- docs/pages/premium.md
- docs/pages/translation.md
- docs/pages/troubleshooting.md
Introduced new pages documenting various fan-made modules for WFRP4e, such as Chat Commander, GM Toolkit, Fan-made Maps, and more. Additionally, updated navigation order for key sections like Active Effects, Macros, Translation, and Troubleshooting.
> [Docs] Add documentation for fan-made modules

- src/documents/actor.js
- src/system/rolls/test-wfrp4e.js
A couple of fixes for Corruption when using a translation.
- corruptionDialog now looks for the localized versions of cool and endurance.
- Now re-rolls look for the localized strength, like the original roll.
For tanslators: If you want that lowercased strengths can be used (for the chat command, for example), you have to change these lines in the lang file.
```
"minor": "Minor",
"moderate": "Moderate",
"major": "Major",
```
Spanish example:
```
"menor": "Menor",
"moderada": "Moderada",
"mayor": "Mayor",
```
Or you can add them, as you prefer.
> Fixes for Localized Corruption

- static/templates/sheets/partials/armour-location.hbs
- style/sheets/actors/_actor.scss
Implements #2552 by restoring 8.* styling for the Armour table
> Restore feedback on Damaged Armour

- scripts/6oSs8qKFNFz2lSmh.js
Applies to SOC Vehicle > Critical > Rigging items: 
- Mast Shattered
- Ruined Sail
- Yard Snapped
> Fix typo in shared SOC ship criticals script

- docs/pages/macros.md
- replace `bypass`with `skipDialog`
- add dialog option notes
- extend chat macro table example to include `modifier` parameter
- remove `help` parameter for table help guidance
- improve readability and usability of script examples
- add notes for rollItemMacro parameters
- convert selected code samples to code blocks for easier copy-paste
> Correct and improve macro help documentation

- src/documents/actor.js
Fixes issue with Prayer tests being rolled twice.
setupTest interface is like this
`_setupTest(dialogClass, testClass, data, context = {}, options={}, roll = true, sendToChat=true)`
so additional option was causing a roll as objects are truthy.
> fix: Prevent setup of Prayer test from rolling
