moo-man/WFRP4e-FoundryVTT

- css/wfrp4e.css
Basically doing what Moerill is suggesting in #136.
> Make default font color in window content light

- modules/actor/actor-wfrp4e.js
- modules/actor/sheet/actor-sheet.js
- modules/apps/stat-parser.js
- modules/hooks/canvas.js
- modules/hooks/getSceneControlButtons.js
- modules/hooks/init.js
- modules/hooks/token.js
- modules/system/audio-wfrp4e.js
- modules/system/effect-wfrp4e.js
- modules/system/hooks.js
- modules/system/migrations.js
- modules/system/opposed-wfrp4e.js
- modules/system/rolls/cast-test.js
- modules/system/rolls/channel-test.js
- modules/system/rolls/prayer-test.js
- modules/system/rolls/test-wfrp4e.js
- modules/system/rolls/trait-test.js
- modules/system/rolls/weapon-test.js
- modules/system/tag-manager.js
- modules/system/utility-wfrp4e.js
- templates/actors/creature/creature-main.html
- templates/apps/homebrew-settings.html
- templates/chat/chat-message.html
- templates/chat/corruption.html
- templates/chat/roll/test-card.html
- templates/dialog/dialog-constant.html
Hi, 
few suggestions for fixes and tweaks after refactor. Great job btw. I hope that those will help, feel free to reject the PR and apply only part of those manually, if not all of them are relevant.
> few fixes (not 100% tested though)

- README.md
- modules/item/item-wfrp4e.js
- modules/system/rolls/cast-test.js
- modules/system/rolls/test-wfrp4e.js
- system.json
- templates/actors/actor-skills.html
- templates/actors/actor-talents.html
- templates/actors/character/character-main.html
> Hotfix 4.0.4

- modules/hooks/combat.js
Fixes deprecation warning when adding token to combat.
> Fix PlaceableObjects#getFlag deprecation warning

- lang/en.json
Hi. While creating the translation file I noticed that the Overcast Reset line was missing. Here is the fix.
By the way, I fixed issues 839 and 689 (journal fixes. Just wanted to see if I could do it). But they are in the core module.
Do you want the fixes? If so, how can I send them to you?
> Added Overcast Reset

- lang/en.json
- modules/item/item-wfrp4e.js
- modules/system/tables-wfrp4e.js
Here are a couple of lines regarding tables.
Also, it seems that you didn't read my message about the Sniper talent.
After the change in the range bands, the script in the Sniper talent should be changed to this:
> Added Localizations

- css/carousel.css
> fix overlay config, the values appeared under the rings

- modules/actor/actor-wfrp4e.js
Makes the scrolling text move upwards when the number increases and move downwards when the number decreases. Which is visually (and psychologically) more impacting.
> Scrolling Text Variation

- modules/item/item-wfrp4e.js
Check for negative Encumbrance in Lightweight items and added Bulky quality flaw encumbrance penalty.
> Added Bulky encumbrance penalty. Check for negative Encumbrance

- modules/item/item-wfrp4e.js
A quick fix for the Bulky flaw, which wasn't adding the extra encumbrance.
> Fix for Bulky flaw

- css/wfrp4e.css
Adding UI compatibility with [Introduce Me](https://github.com/WBHarry/introduce-me). Now (almost) all of it should be readable in WFRP.
> Compatibility with Introduce Me

- modules/system/rolls/trait-test.js
- modules/system/rolls/weapon-test.js
Suppress Impenetrable message when non-critical.
Trait Test also handles impenetrable.
> Impenetrable

- modules/system/config-wfrp4e.js
The description of the Blinded effect is incorrectly assigned.
> Fix for Blinded effect

- modules/actor/actor-wfrp4e.js
- modules/system/audio-wfrp4e.js
- modules/system/rolls/cast-test.js
- modules/system/rolls/test-wfrp4e.js
- modules/system/tables-wfrp4e.js
Fixes for errors and warnings I've come across while working on v10 compatibility for GM Toolkit.
> Fix datamodel warnings and roll deprecations

- modules/apps/wfrp-browser.js
- modules/system/config-wfrp4e.js
- modules/system/tables-wfrp4e.js
- static/lang/en.json
This will allow to translate the "Target" in the scatter table. Also allows to translate the Location labels in the browser.
> Localizations

- modules/actor/sheet/actor-sheet.js
- modules/item/item-wfrp4e.js
- modules/system/utility-wfrp4e.js
This allows the separation of petty magic (for grimoire, xp costs, dialog, etc.) to be used if the magic lores are translated too.
> Localized petty magic

- modules/item/item-wfrp4e.js
- static/lang/en.json
- static/templates/actors/actor-combat.hbs
Simply adds localization for the new qualities' "OR".
> Localization

- .gitignore
- foundryconfig.json
- static/css/wfrp4e.css
Changes:
1. Added `.idea/` to `.gitignore`. It's a folder that every JetBrains' IDE creates like WebStorm or PhpStorm (and I'm using the latter)
2. Removed the `foundryconfig.json` from GIT. It holds local path and should not be in repository (as every dev uses other path)
3. Fixed Issue #48
4. Added support for Foundry's native Filepicker's, more specifically for Favorites (so they can be readable)
> Small css fixes

- modules/actor/actor-wfrp4e.js
- modules/system/tables-wfrp4e.js
- modules/system/utility-wfrp4e.js
Resolves moo-man/WFRP4e-FoundryVTT#1623
> Fixed critical going out of bounds on -20 modifier

- static/css/wfrp4e.css
- static/templates/actors/actor-inventory.hbs
- static/templates/actors/vehicle/vehicle-cargo.hbs
Resolves moo-man/WFRP4e-FoundryVTT#1527
> added toggles to equippable items when display is collapsed

- modules/actor/actor-wfrp4e.js
- static/lang/en.json
> Added support for creating active effects for "seconds" and "days" duration

- modules/apps/market-wfrp4e.js
- modules/system/chat-wfrp4e.js
- static/lang/en.json
> Limit the number of times credit can be gained to the original split amount.

- modules/apps/roll-dialog/attack-dialog.js
- modules/model/item/weapon.js
- modules/system/area-helpers.js
Minor fixes to supress errors I was getting, mostly around weapons on creatures and attack tests
> Minor fixes

- modules/apps/effect-config.js
- modules/apps/effect-script-config.js
- modules/apps/script-config.js
- static/css/wfrp4e.css
- static/templates/apps/script-config.hbs
- Widened sheet by 30 pixels so that ProseMirror's controls are in single line
- added parchment background to match that of the RollTable (probably not the best looking, but easiest approach, because it doesn't involve the need to change prosemirror's font colors etc)  
- Modified Script Config so script textarea fills the available area (using flex box), and it's working well with dynamically changing form based on trigger)
- Made config a little bit bigger by default
- Set font to 12px monospace. Personally I think it looks a little better 
- That said I think there are google fonts that would work a lot better/have a cleaner look, for example [Source Code Pro](https://fonts.google.com/specimen/Source+Code+Pro?preview.text=let%20wounds%20%3D%20this.actor.status.wounds%20if%20(wounds.val …
> Styling improvements for Active Effect Sheet and Script Config

- modules/hooks/ready.js
> Fix broken cursors when Foundry uses routePrefix

- modules/system/config-wfrp4e.js
- static/lang/en.json
* Conditions localization and updates
* Conditions updates
* isMelee/isRanged
> Conditions localization and updates (#1906)

- modules/apps/chargen/skills-talents.js
Fix chargen not allowing to submit skills and talents when species has no random talents
Bug reported here: https://discord.com/channels/449845411344154634/712500603250802829/1233910940513337444
> Fix chargen not allowing to submit skills and talents

- scripts/rUGSx06BuBvX9kgf.js
Adds Resolute to the damage breakdown.
P.S. Nice that now we can send PRs for existing effects!
> Resolute breakdown message

- modules/model/item/weapon.js
- modules/system/utility-wfrp4e.js
This Pull Request fixes `rangeBands` houserule related functions, that were trying to call `getFlag()` on Data Model instead of the Document, which prevented Actor Sheet and Token Action HUD from rendering correctly. 
- Fixes #1989
> Fix rangeBands houserule breaking Actor Sheet etc.

- scripts/IukS0clr1yAleacc.js
- scripts/eAtqyBd1HsDWuBuI.js
Closes https://github.com/moo-man/WFRP4e-FoundryVTT/issues/2022
> Fix for Amputations

- modules/apps/roll-dialog/cast-dialog.js
- modules/apps/roll-dialog/channelling-dialog.js
- modules/apps/roll-dialog/characteristic-dialog.js
- modules/apps/roll-dialog/prayer-dialog.js
- modules/apps/roll-dialog/skill-dialog.js
- modules/apps/roll-dialog/trait-dialog.js
- modules/apps/roll-dialog/weapon-dialog.js
the `get vehicle()` getter is located in `StandardActorModel`, not in `ActorWfrp4e`, so the proper path needs `system`.
> Get vehicle from Data Model, not Actor

- modules/system/rolls/test-wfrp4e.js
> Fix extended tests not being possible to roll

- modules/system/rolls/test-wfrp4e.js
> Fix fortune not subtracting (Fixes #2211)

- modules/apps/stat-parser.js
- modules/system/migrations.js
- modules/system/socket-handlers.js
- modules/system/trade/trade-generator.js
Not sure if I was tripping, but `game.system.model` was not working for me at all and `game.model` does. 
Probably best to double check if it's really broken before merging this PR
> minor fixes to various parts of the system

- system.json
Fixed manifest deprecation warning.
- Source: https://github.com/foundryvtt/foundryvtt/issues/9999
> [Breaking] Update grid config in manifest to v12

- modules/system/chat-wfrp4e.js
- modules/system/rolls/test-wfrp4e.js
- scripts/xS2su09zcza9du09.js
- static/lang/en.json
Since Japanese translation uses a different translation for the strength of Corruption, three keys were added to the language file.
> corruption strength localize issue

- modules/hooks/init.js
- modules/system/config-wfrp4e.js
- static/lang/en.json
- Added UiA Bleeding settings
- Implemented UiA Bleeding condition
> Add optional UiA Bleeding version

- modules/system/chat-wfrp4e.js
> Fix to Apply Hack with ArmourV2

- modules/model/actor/components/details.js
- src/apps/sheets/actor/standard-sheet.js
- static/css/wfrp4e.css
- static/templates/actors/actor-notes.hbs
- static/templates/actors/creature/creature-notes.hbs
- static/templates/sheets/actor/character/character-header.hbs
- static/templates/sheets/actor/characteristic-header.hbs
- static/templates/sheets/actor/creature/creature-notes.hbs
- static/templates/sheets/actor/npc/npc-notes.hbs
- style/sheets/actors/_actor.scss
- style/sheets/actors/_creature.scss
- style/sheets/actors/_npc.scss
I've moved some of the model properties from character to standard model - for NPC and Creatures. This incudes: 
- hair colour, eyes colour, age, width, height, specials. 
Please accept this change :-) 
it will help me with: 
- support for automate token height in context of Wall-height and therefore, autocover/vision calculation 
- better support for my AI-gen npcs, which i want to get back to.
> add description details to npcs and creatures

- docs/pages/advanced/advanced.md
- docs/pages/advanced/lore.md
- docs/pages/advanced/species.md
- docs/pages/advanced/trade.md
- docs/pages/advanced/worldScripts.md
Expanded the Advanced Topics documentation with comprehensive guides on adding Lores, Species, Subspecies and World Scripts. Included specific code examples.
> [Docs] Expanded the Advanced Topics documentation

- style/theme/_journal.scss
Fixed the path of the bookshelf background image.
> Fixed bookshelf background

- scripts/qmOt7h17hGAKqQe0.js
Fix for the Dome script.
Closes #2474
> Fix for Dome

- scripts/7Ck0fkzE4WQ62qVe.js
- scripts/a7pEvCycVnFBXGAQ.js
- scripts/iT3C15fMyQrj1RmG.js
- scripts/rnioLwiJP7ps5Jwy.js
Adds or fixes localizations for a few scripts.
> Localization fixes for scripts

- src/documents/actor.js
There were 2 little typos in actor file that seemed to cause an error on extended test.
Should address #2545
> fix: Fixes Issue #2545 by fixing typos

- scripts/6xTtJEhRc4OjcDTf.js
- scripts/7w7QA7GBhzZ98OS0.js
- scripts/8TRiAJ8thIKE4IoL.js
- scripts/pR4Q2OnPxXtwRVli.js
- scripts/yDvxF9llUYwJg0sE.js
- src/apps/chargen/career.js
- src/documents/item.js
- src/model/actor/character.js
- src/model/item/components/properties.js
- src/model/item/container.js
- src/model/item/skill.js
- src/sheets/actor/base.js
- src/system/rolls/test-wfrp4e.js
- src/system/tables-wfrp4e.js
- static/templates/apps/trade/trade-dialog.hbs
- static/templates/sheets/partials/ranged-weapons.hbs
Fixes for some deprecation warnings.
> fixed deprecation warnings

- src/apps/chargen/char-gen.js
- src/documents/actor.js
- src/documents/message.js
- src/system/opposed-handler.js
- src/system/rolls/test-wfrp4e.js
- src/system/socket-handlers.js
This is a system-specific PR related to: https://github.com/moo-man/WarhammerLibrary-FVTT/pull/25
> awaitable sockets
